name: bookcollection
description: A new Flutter project.

# The version of your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies section should be at the root level, not inside "flutter".
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  http: ^0.13.4
  provider: ^6.0.5
  # Add other dependencies if required (e.g., path_provider, etc.)

# Assets section under flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/book.png
    - assets/images/3rd.png
    - assets/images/Book1.jpg
    - assets/images/do.jpeg
    - assets/images/gr.png
    - assets/images/sc.png


dev_dependencies:
  flutter_test:
    sdk: flutter

# Add more configurations here if necessary
